services:
  os-release-tracker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: os-release-tracker

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - ./os_tracker.db:/app/os_tracker.db