name: WatchTower CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy WatchTower
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 2299
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            /opt/WatchTower/deploy.sh



            